### PR TITLE
Correctly handle strings with dollar signs (and anything else, if I've gotten it right)

### PR DESCRIPTION
**Pull request by gnprice**
As a comment suggests, the current version can produce the wrong result in some cases. This bug can be turned into an injection if a user can cause one of the values in the hash to contain a double dollar sign, looking something like

```
$$; SELECT 'lol'; --
```

In this series, we reorganize the tests, then add a test for this bug; fix the bug; and refactor the code a bit and add extensive comments referring to the PostgreSQL docs to document why it all works.

To fix the bug, we replace dollar-quoting with a different PostgreSQL string constant syntax, one that I believe I've used 100% correctly here so that there are no more injections.

### CODE REVIEW

**Comment by gnprice** [comment]
Some formatting in the tests revised after comments from @teeparham.

**Comment by seamusabshere** [comment]
@gnprice what an exemplary pull request. pure quality. thank you!

**Comment by seamusabshere** [comment]
released in gem version 1.1.7

**Comment by gnprice** [comment]
Thanks! Love the fast response.

**Pull request merged**
